# Generated by Django 5.0.6 on 2024-06-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0002_alter_sitebanner_image_alter_sitebanner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='image',
            field=models.ImageField(upload_to='uploads/images/banners', verbose_name='banner image'),
        ),
    ]
