# Generated by Django 5.0.6 on 2024-06-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0003_alter_sitebanner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='siteBanner',
        ),
    ]
