# Generated by Django 5.0.6 on 2024-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_module', '0004_delete_sitebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='banner title')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='banner address')),
                ('image', models.ImageField(upload_to='uploads/images/banners', verbose_name='banner image')),
                ('is_active', models.BooleanField(verbose_name='active/inactive')),
                ('position', models.CharField(choices=[('home_page', 'صفحه اصلی'), ('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه جزئیات محصولات'), ('about_us', 'درباره ما')], max_length=200, verbose_name='banner position')),
            ],
        ),
    ]
