# Generated by Django 5.0.6 on 2024-06-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='siteBanner',
        ),
    ]
