# Generated by Django 5.0.6 on 2024-06-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_image_product_remove_video_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='videos',
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ManyToManyField(related_name='images', to='products.product'),
        ),
        migrations.AddField(
            model_name='video',
            name='product',
            field=models.ManyToManyField(related_name='video', to='products.product'),
        ),
    ]
