# Generated by Django 5.0.6 on 2024-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_images_remove_product_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Mobile_Phones', 'Mobile Phones'), ('Smart_TV', 'Smart TV'), ('Smart_Watch', 'Smart Watch'), ('Laptops', 'Laptops'), ('Drones', 'Drones'), ('Headphones', 'Headphones')], max_length=255),
        ),
    ]
