# Generated by Django 5.0.6 on 2024-06-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='item_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='product',
            name='item_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
