# Generated by Django 5.0.6 on 2024-06-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(choices=[('off-box', 'Off-box'), ('detail-box', 'Detail-box')], default='', max_length=100),
        ),
    ]
