# Generated by Django 5.0.6 on 2024-06-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='set_as_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(choices=[('off-box', 'Off-box'), ('detail-box', 'Detail-box'), ('banner', 'Banner')], default='', max_length=100),
        ),
    ]
