# Generated by Django 5.0.6 on 2024-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_set_as_banner_alter_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='set_as_site_background',
            field=models.BooleanField(default=False),
        ),
    ]
